parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

if [ "$color_prompt" = yes ]; then
    PS1=$PS1 + "\$(parse_git_branch)\[\033[00m\] \$ "
else
    PS1=$PS1 + "\$(parse_git_branch) \$ "
fi

# Windows WSL specific
export DISPLAY=:0
export DOCKER_HOST=tcp://0.0.0.0:2375
